### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ghost** [thowi/feedly-filter-chrome-extension#1] opened 2015-11-11 19:29 UTC
Hey, thanks for the extension. I am getting the following exception when the slider is moving:

```
Uncaught TypeError: Cannot read property 'getAttribute' of null
Feedly.getPopularityForRow 
@ feedly.js:53(anonymous function) 
@ feedly.js:107Feedly.filterRows 
@ feedly.js:106Filter.filterRows 
@ filter.js:81Filter.onRangeInput 
@ filter.js:47
```

**Comment by thowi** [comment] 2015-11-12 09:29
Thanks for the report, Vitali!

The code in question is here:
Feedly.prototype.getPopularityForRow = function(row) {
  var popularityElement = row.querySelector('.recommendationInfo span');
  return parseInt(popularityElement.getAttribute('data-engagement'));
};

It looks like popularityElement was not found in your case.
Do you have that element in your DOM? Do you see the "popularity score" next to the item?

I cannot reproduce the issue, as I always have that element and hence don't see the error.

Cheers

**Comment by thowi** [comment] 2016-05-17 19:49
Closing as obsolete. Please re-open if you still see this.

**Closed as completed by thowi** 2016-05-17 19:49 UTC
